### ISSUE TITLE
Changed bot text in manifest.json file

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-apps-icebreaker#219] opened 2022-01-06 13:25 UTC
Hello,

I changed the text 
"appDescription": {
    "Value": "Icebreaker is a cute little bot that randomly pairs team members up every week to help the team build trust and personal connections.",
    "Description": "The app (and bot) description."

And the text is changed, but only when you click in team, three dots, managed team, apps, click on bot
see this printscreen
![printscreen bot](https://user-images.githubusercontent.com/49586227/148389108-b6dc4666-c874-4b42-8248-cdba01e61c39.png)

If you are in the specific team and receive an invite of the bot in chats in teams the text is not changed. See printscreen
![printscreen bot1](https://user-images.githubusercontent.com/49586227/148389535-7997e7bc-247d-4bcf-bc13-d6ea5cb076a6.png)

Where can i change this text? or is this not possible?

Greet,
Linda

**Comment by Porkai-Pandian** [comment] 2022-01-13 19:31
Hi @LindaSchaar,

Thank you for raising the query, if you want to modify the text mentioned you need to customize the app by modifying it in Resources.resx file and redeploy the app.

**Comment by LindaSchaar** [comment] 2022-01-20 10:44
@Porkai-Pandian with which application can I open the file resources.resx ?

**Comment by Porkai-Pandian** [comment] 2022-01-21 18:46
@LindaSchaar you can modify the resource file available in this path (microsoft-teams-apps-icebreaker/Source/Icebreaker/Properties/), you can use Visual Studio, Visual Studio Code or any text editor to open the file.

**Comment by LindaSchaar** [comment] 2022-02-10 15:40
@Porkai-Pandian thanks i changed it in the file resources.resx. But you need to change it on 3 spots in this file? and change it in the manifest and thats it?

**Comment by LindaSchaar** [comment] 2022-02-15 09:29
@Porkai-Pandian unfortunally it does not work. I change it in the resources.resx file each other week. I changed it in the manifest.json file and I changed it in parameters.json file

And it is the same results as my post at the first time

![image](https://user-images.githubusercontent.com/49586227/154033204-dd2dc0d0-66e5-413d-8289-6a082fd3d3e3.png)

Please assist

**Comment by Porkai-Pandian** [comment] 2022-04-07 00:03
Duplicate of #227, hence closing this issue.

**Closed by Porkai-Pandian** 2022-04-07 00:03 UTC
Labels: answered
