### ISSUE TITLE
NullReferenceException while sending notification to the users

### ISSUE THREAD

**Issue by maxhaensel** [OfficeDev/microsoft-teams-apps-icebreaker#91] opened 2020-07-31 12:09 UTC
Hello, I´ve got an Issue using Icebreaker App.

We successfully deployed the bot in an Azure infrastructure and added the bot in a Channel in MS Teams.

### Main problem

we have the problem that not every user receives an invitation, because the Bot throws an error during execution.

Logfile from Azure
```json
{
   "parsedStack":[
      {
         "assembly":"IceBreaker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
         "method":"Icebreaker.Helpers.AdaptiveCards.PairUpNotificationAdaptiveCard.IsGuestUser",
         "level":0,
         "line":0
      },
      {
         "assembly":"IceBreaker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
         "method":"Icebreaker.Helpers.AdaptiveCards.PairUpNotificationAdaptiveCard.GetCard",
         "level":1,
         "line":0
      },
      {
         "assembly":"IceBreaker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
         "method":"Icebreaker.IcebreakerBot+<NotifyPair>d__17.MoveNext",
         "level":2,
         "line":0
      },
      {
         "assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxx",
         "method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
         "level":3,
         "line":0
      },
      {
         "assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxx",
         "method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
         "level":4,
         "line":0
      },
      {
         "assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxx",
         "method":"System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd",
         "level":5,
         "line":0
      },
      {
         "assembly":"IceBreaker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
         "method":"Icebreaker.IcebreakerBot+<MakePairsAndNotify>d__7.MoveNext",
         "level":6,
         "line":0
      }
   ],
   "outerId":"0",
   "message":"Object reference not set to an instance of an object.",
   "type":"System.NullReferenceException",
   "id":"23981744"
}
```

I guess the problem starts with the `pair` object. [IcebreakerBot.cs](https://github.com/OfficeDev/microsoft-teams-icebreaker-app/blob/677f5f01893dff17ea4f0d2e5d66a66cc54b143d/Source/Icebreaker/IcebreakerBot.cs#L89) 

Could it be possible that the nullpointer object came from [IcebreakerBot.cs](https://github.com/OfficeDev/microsoft-teams-icebreaker-app/blob/677f5f01893dff17ea4f0d2e5d66a66cc54b143d/Source/Icebreaker/IcebreakerBot.cs#L390) ? 

while searching through the code I ended up here [PairUpNotificationAdaptiveCard.cs](https://github.com/OfficeDev/microsoft-teams-icebreaker-app/blob/677f5f01893dff17ea4f0d2e5d66a66cc54b143d/Source/Icebreaker/Helpers/AdaptiveCards/PairUpNotificationAdaptiveCard.cs#L49).

I am not sure why a user is a null pointer. I guess this is because one of the user in the channel is missing company mail.
I do not understand how the `pair.Item1.Id` is connected to the user in Azure AD to find out which Azure AD user is causing the problem.
[this...TrackTrace(.... {pair.Item1.Id} ....);](https://github.com/OfficeDev/microsoft-teams-icebreaker-app/blob/677f5f01893dff17ea4f0d2e5d66a66cc54b143d/Source/Icebreaker/IcebreakerBot.cs#L287)

### The second problem
The second problem is when the Error is raised the entire loop breaks and only a subset of the matches get notified instead of only the failed one get not notified. 
Wouldn't it be better to catch the error in the foreach-block as well so the notification can continue.

```cs
foreach (var pair in this.MakePairs(optedInUsers).Take(this.maxPairUpsPerTeam))
    {
        try
            {
                usersNotifiedCount += await this.NotifyPair(connectorClient, team.TenantId, teamName, pair);
                pairsNotifiedCount++;
                .........
    }
```

very thanks 
max

**Comment by CraigStuntz** [comment] 2020-10-27 18:02
We're seeing this as well (the first problem). To be precise, the exception is in `PairUpNotificationAdaptiveCard.IsGuestUser` on the following code:
```csharp
return account.UserPrincipalName.IndexOf(ExternallyAuthenticatedUpnMarker, StringComparison.InvariantCultureIgnoreCase) >= 0;
```
Apparently `UserPrincipalName` is `null` in some cases?

**Comment by CraigStuntz** [comment] 2020-10-27 18:13
I think this is a duplicate of #69

**Comment by maxhaensel** [comment] 2020-12-18 14:21
@CraigStuntz thanks for linking the issue to #69

**Comment by v-royavinash** [comment] 2021-12-17 09:42
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by CraigStuntz** [comment] 2021-12-17 14:40
@v-royavinash It looks like the code which fails if `account.UserPrincipalName` is null is still there in the main branch. So I think this is still a bug.

**Comment by gsv022** [comment] 2022-08-09 07:05
Hi @maxhaensel ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to close the long pending issues with no resolution/responses. You may always open a new issue if you are still facing the issue. We are closing this request. 
Thank you!

**Closed by gsv022** 2022-08-09 07:05 UTC
